export const FreelanceMarketplaceABI = [
  "function postJob(string title, string description, uint256 budget, uint8 requiredSkill, uint8 minimumTier, uint256 deadline) payable returns (uint256)",
  "function postJobWithToken(string title, string description, uint256 budget, address paymentToken, uint8 requiredSkill, uint8 minimumTier, uint256 deadline) returns (uint256)",
  "function applyForJob(uint256 jobId, string proposal)",
  "function acceptApplication(uint256 jobId, uint256 applicationIndex)",
  "function submitDeliverable(uint256 jobId, string deliverableHash)",
  "function approveDeliverable(uint256 jobId, uint8 rating, string review)",
  "function raiseDispute(uint256 jobId)",
  "function cancelJob(uint256 jobId)",
  "function claimAfterTimeout(uint256 jobId)",
  "function canClaimAutoRelease(uint256 jobId) view returns (bool)",
  "function timeUntilAutoRelease(uint256 jobId) view returns (uint256)",
  "function setReferrer(address referrer)",
  "function addSupportedToken(address token)",
  "function removeSupportedToken(address token)",
  "function supportedTokens(address token) view returns (bool)",
  "function jobs(uint256 jobId) view returns (uint256 id, address client, address freelancer, string title, string description, uint256 budget, uint256 escrowAmount, address paymentToken, uint8 requiredSkill, uint8 minimumTier, uint8 status, uint256 createdAt, uint256 deadline, uint256 deliverableSubmittedAt, string deliverableHash, address referredBy)",
  "function getJobApplications(uint256 jobId) view returns (tuple(address freelancer, string proposal, uint256 timestamp, bool accepted)[])",
  "function getAllJobs() view returns (tuple(uint256 id, address client, address freelancer, string title, string description, uint256 budget, uint256 escrowAmount, address paymentToken, uint8 requiredSkill, uint8 minimumTier, uint8 status, uint256 createdAt, uint256 deadline, uint256 deliverableSubmittedAt, string deliverableHash, address referredBy)[])",
  "function getOpenJobs() view returns (tuple(uint256 id, address client, address freelancer, string title, string description, uint256 budget, uint256 escrowAmount, address paymentToken, uint8 requiredSkill, uint8 minimumTier, uint8 status, uint256 createdAt, uint256 deadline, uint256 deliverableSubmittedAt, string deliverableHash, address referredBy)[])",
  "function getClientJobs(address client) view returns (uint256[])",
  "function getFreelancerApplications(address freelancer) view returns (uint256[])",
  "function platformFee() view returns (uint256)",
  "function platformWallet() view returns (address)",
  "event JobPosted(uint256 indexed jobId, address indexed client, string title, uint256 budget, uint8 requiredSkill)",
  "event ApplicationSubmitted(uint256 indexed jobId, address indexed freelancer, string proposal)",
  "event ApplicationAccepted(uint256 indexed jobId, address indexed freelancer)",
  "event JobStarted(uint256 indexed jobId, address indexed freelancer)",
  "event DeliverableSubmitted(uint256 indexed jobId, string deliverableHash)",
  "event JobCompleted(uint256 indexed jobId, address indexed freelancer, uint256 amount)",
  "event JobDisputed(uint256 indexed jobId)",
  "event DisputeResolved(uint256 indexed jobId, bool inFavorOfFreelancer)",
  "event JobCancelled(uint256 indexed jobId)",
  "event AutoReleaseClaimed(uint256 indexed jobId, address indexed freelancer, uint256 amount, uint256 penalty)",
  "event ReferralRewardPaid(address indexed referrer, address indexed referee, uint256 indexed jobId, uint256 amount)",
  "event TokenAdded(address indexed token, string symbol)",
  "event TokenRemoved(address indexed token)",
] as const;
